### ISSUE TITLE
Unable to set up newly installed component

### ISSUE THREAD

**Issue by DerZoger** [hg1337/homeassistant-dwd#2] opened 2022-05-14 23:50 UTC
Hi!

First of all thanks for creating this awesome component, the ability to pull current weather measurements is really great!

I've followed the steps for initial set up you've outline in the “Installation and Configuration” section, and I am able to find the component in the integrations list and the correct station close to me (Station: 10381 (Berlin-Dahlem (FU)) is also selected automatically. However, when I choose “Continue” the set-up fails with “Unknown error occurred”. Simultaneously, the following error is logged:

Logger: aiohttp.server
Source: custom_components/dwd/config_flow.py:45
Integration: Deutscher Wetterdienst (documentation)
First occurred: 01:18:32 (5 occurrences)
Last logged: 01:30:16

Error handling request
Traceback (most recent call last):
  File “/usr/local/lib/python3.9/site-packages/aiohttp/connector.py”, line 1154, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File “/usr/local/lib/python3.9/site-packages/aiohttp/connector.py”, line 880, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File “/usr/local/lib/python3.9/site-packages/aiohttp/resolver.py”, line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File “/usr/local/lib/python3.9/asyncio/base_events.py”, line 856, in getaddrinfo
    return await self.run_in_executor(
  File “/usr/local/lib/python3.9/concurrent/futures/thread.py”, line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File “/usr/local/lib/python3.9/socket.py”, line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File “/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py”, line 435, in _handle_request
    resp = await request_handler(request)
  File “/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py”, line 504, in _handle
    resp = await handler(request)
  File “/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py”, line 117, in impl
    return await handler(request)
  File “/usr/src/homeassistant/homeassistant/components/http/security_filter.py”, line 60, in security_filter_middleware
    return await handler(request)
  File “/usr/src/homeassistant/homeassistant/components/http/forwarded.py”, line 222, in forwarded_middleware
    return await handler(request)
  File “/usr/src/homeassistant/homeassistant/components/http/request_context.py”, line 28, in request_context_middleware
    return await handler(request)
  File “/usr/src/homeassistant/homeassistant/components/http/ban.py”, line 79, in ban_middleware
    return await handler(request)
  File “/usr/src/homeassistant/homeassistant/components/http/auth.py”, line 219, in auth_middleware
    return await handler(request)
  File “/usr/src/homeassistant/homeassistant/components/http/view.py”, line 137, in handle
    result = await result
  File “/usr/src/homeassistant/homeassistant/components/config/config_entries.py”, line 205, in post
    return await super().post(request, flow_id)
  File “/usr/src/homeassistant/homeassistant/components/http/data_validator.py”, line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File “/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py”, line 109, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File “/usr/src/homeassistant/homeassistant/data_entry_flow.py”, line 260, in async_configure
    result = await self._async_handle_step(
  File “/usr/src/homeassistant/homeassistant/data_entry_flow.py”, line 335, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File “/config/custom_components/dwd/config_flow.py”, line 45, in async_step_user
    result = await clientsession.head(
  File “/usr/local/lib/python3.9/site-packages/aiohttp/client.py”, line 535, in _request
    conn = await self._connector.connect(
  File “/usr/local/lib/python3.9/site-packages/aiohttp/connector.py”, line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File “/usr/local/lib/python3.9/site-packages/aiohttp/connector.py”, line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File “/usr/local/lib/python3.9/site-packages/aiohttp/connector.py”, line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host opendata.dwd.de:443 ssl:default [Try again]

To me, this indicates some kind of SSL issue. Is it possible that this is caused by something similar to the SSL issue patched in the “simple_dwd_weatherforecast” library that FL550's DWD integration uses? https://github.com/FL550/simple_dwd_weatherforecast/releases/tag/v1.1.4

In case it's helpful, I'm running “Home Assistant Core 2022.5.4”.

I would really appreciate if you could take the time and assist me with the issue I'm facing!

Kind regards,
Christopher

**Comment by hg1337** [comment] 2023-01-03 04:06
Closing this issue as I could not reproduce it and there was no further feedback. If you still experience issues, feel free to re-open.

**Closed by hg1337** 2023-01-03 04:06 UTC
