### ISSUE TITLE
The integration dwd_weather is using the deprecated forecast attribute

### ISSUE THREAD

**Issue by heinemannj** [hg1337/homeassistant-dwd#11] opened 2023-09-07 11:14 UTC
After upgrading of HA to

```
Home Assistant 2023.9.0
Supervisor 2023.08.3
Operating System 10.5
Frontend 20230906.1 - latest
```

the following waring pop's up:

`The integration dwd_weather is using the deprecated forecast attribute.`

Please check:

https://www.home-assistant.io/blog/2023/09/06/release-20239/#weather-forecast-service

**Comment by ctyd** [comment] 2023-09-17 14:54
i have the same problem

**Comment by hg1337** [comment] 2023-09-17 19:22
Hi all, thank you for reporting this. Unfortunately, I'm unable to reproduce it. First of all a b nit background information for you:

With version 2023.8.1 I already introduced the new mechanism, see release notes at https://github.com/hg1337/homeassistant-dwd/releases. There is a new entity without the _daily or _hourly suffix that returns daily and hourly forecasts in the new way in one single entity:

![image](https://github.com/hg1337/homeassistant-dwd/assets/76538974/7950cd68-4fbe-4713-88fb-12bcd88e11ba)

The currently _daily and _hourly entities return the forecast both ways for backward compatibility with third party weather cards, but this doesn't seem to produce the warning here as long as the new mechanism is provided, at least for now.

But I believe I now know what the problem is: @heinemannj in the message it says "dwd_weather".  However, this component is only "dwd". You are probably using https://github.com/FL550/dwd_weather. (Why both exist see https://github.com/hg1337/homeassistant-dwd/blob/main/questions_and_answers.md)

**Comment by hg1337** [comment] 2023-09-17 19:38
Closing this as "can't reproduce", because I'm pretty sure it's about the other integration and I believe my integration follows already the new mechanism described in the blog. But feel free to reopen it, if you can produce this with the current version (2023.8.2) of "dwd" (not "dwd_weather").

**Closed by hg1337** 2023-09-17 19:38 UTC

**Comment by heinemannj** [comment] 2023-09-18 06:16
> But I believe I now know what the problem is: @heinemannj in the message it says "dwd_weather". However, this component is "dwd". You are probably using https://github.com/FL550/dwd_weather or both in parallel. (Why both exist see https://github.com/hg1337/homeassistant-dwd/blob/main/questions_and_answers.md)

Yes you are right - I'm using the other DWD integration.
Sorry for the noise.
